package com.codesage.domain.auth.dto.request;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;

/**
 * Request body for the GitHub OAuth callback endpoint.
 *
 * <p>The frontend receives the OAuth code from GitHub's redirect
 * and POSTs it to {@code POST /api/v1/auth/github/callback}.
 */
@Schema(description = "GitHub OAuth authorization code received from the GitHub redirect")
public record GitHubCallbackRequestDto(

        @Schema(description = "OAuth authorization code from GitHub", example = "abc123xyz")
        @NotBlank(message = "Authorization code must not be blank")
        String code,

        @Schema(description = "CSRF state token generated by the frontend", example = "random-state-value")
        @NotBlank(message = "State token must not be blank")
        String state
) {}
